### PR TITLE
Trying to make test type dynamic - WIP

### PR DESCRIPTION
**Pull request by opishcheiko**

### CODE REVIEW

**Comment by opishcheiko** [comment]
@Jnegrier is there any way to test the plugin? I run the tests locally - it's all good, but I wanted to test my condition for Jenkins.. Any way I can play with it and not break delta?

**Comment by Jnegrier** [comment]
> @Jnegrier is there any way to test the plugin? I run the tests locally - it's all good, but I wanted to test my condition for Jenkins.. Any way I can play with it and not break delta?

A hundred apologies, I just saw your message now, to try it as it would be in Jenkins, run the tests like `TEST_TYPE=<TestType> mvn clean test -Dsurefire.suiteXmlFiles=suites/TestSuite1.xml`that would pass `TEST_TYPE` to the plugin

**Comment by Jnegrier** [comment]
> > @Jnegrier is there any way to test the plugin? I run the tests locally - it's all good, but I wanted to test my condition for Jenkins.. Any way I can play with it and not break delta?
> 
> A hundred apologies, I just saw your message now, to try it as it would be in Jenkins, run the tests like `TEST_TYPE=<TestType> mvn clean test -Dsurefire.suiteXmlFiles=suites/TestSuite1.xml`that would pass `TEST_TYPE` to the plugin

It also could be something like `TEST_TYPE='Integration Tests' && mvn clean test -Dsurefire.suiteXmlFiles=suites/TestSuite1.xml`

**Comment by opishcheiko** [comment]
okay, genius, you could have pretended it's not that easy ahaha
Seems to work @Jnegrier 
Screenshot 2020-08-19 at 11 45 15

**Comment by Jnegrier** [comment]
> okay, genius, you could have pretended it's not that easy ahaha
> Seems to work @Jnegrier
> Screenshot 2020-08-19 at 11 45 15

**Comment by Jnegrier** [comment]
I closed it by mistake, sorry. its really cool that the modification is so easy 🦜

**Comment by opishcheiko** [comment]
Can I merge and hope it doesn't break anything? @Jnegrier

**Comment by Jnegrier** [comment]
> Can I merge and hope it doesn't break anything? @Jnegrier

Sure, go ahead, is not going to break anything. Because the process to publish a new version in the central repository in Maven is manual. We can publish a new version later in a call

**Pull request merged**
